sudo: required
services:
  -docker
script:
  -docker build  -t amirrezasalamat/rumi_jokes ./
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push amirrezasalamat/rumi_jokes